### ISSUE TITLE
Task OOP? 

### ISSUE THREAD

**Issue by nandhasuhendra** [savanahagusta/PKL#1]
Task oop yg disuruh waktu hari jumat push ke github 👌🏿

**Comment by savanahagusta** [comment]
Siap, sudah di push ke folder ruby2

**Comment by nandhasuhendra** [comment]
> Siap, sudah di push ke folder ruby2

Penamaan variable, class dan method tolong diperbaiki..

contoh:
```ruby
class Convertable
  def to_json(args)
      # some beautifull code
  end
end
```

```ruby
users = { lists: [{name: 'Savana'}, {name: 'Mpuchan'}]  }

users[:lists].each do |list|
  list.each do |name, value|
    puts "Nama pengguna yang terdafatar #{value}"
  end
end
```

cc @savanahagusta

**Comment by savanahagusta** [comment]
> > Siap, sudah di push ke folder ruby2
> 
> Penamaan variable, class dan method tolong diperbaiki..
> 
> contoh:
> 
> ```ruby
> class Convertable
>   def to_json(args)
>       # some beautifull code
>   end
> end
> ```
> 
> ```ruby
> users = { lists: [{name: 'Savana'}, {name: 'Mpuchan'}]  }
> 
> users[:lists].each do |list|
>   list.each do |name, value|
>     puts "Nama pengguna yang terdafatar #{value}"
>   end
> end
> ```
> 
> cc @savanahagusta

negara = { country: [{name: 'Indonesia'},{name: 'India'},{name: 'Korea'},{name:'Turki'}] , 
                  region: [{zone: 'Asia Tenggara'},{zone: 'Asia Selatan'},{zone: 'Asia Timur'},{zone:'Asia Barat'}]
                }
k = 1
negara[:country].each do |list| 
   list.each do |name, value|
      puts "#{k}. #{value}"
      k = k+1
   end
end

kak, bagaimana cara manggil region yang zone 'Asia Tenggara' saja tanpa yang lainnya?
apa masih ada salah penulisan hashnya?

cc @nandhasuhendra

**Comment by nandhasuhendra** [comment]
Untuk memudahkan bisa dijadikan satu aja..

```ruby
negara = {
  country: [
     { name: 'Indonesia', region: 'Asia Tenggara'},
     { name: 'Qatar', region: 'Asia Timur'} 
 ] 
} 
```

**Comment by savanahagusta** [comment]
> Untuk memudahkan bisa dijadikan satu aja..
> 
> ```ruby
> negara = {
>   country: [
>      { name: 'Indonesia', region: 'Asia Tenggara'},
>      { name: 'Qatar', region: 'Asia Timur'} 
>  ] 
> } 
> ```

oke saya coba dulu kak

**Comment by savanahagusta** [comment]
Sudah saya ubah kak, folder ruby2 yang folder negara nya aja.
